-- INSERT INTO user_tbl (uid, isaccountnonexpired,isaccountnonlocked,iscredentialsnonexpired, isenabled, password, role, username ) VALUES
--                                                       ('1','true', 'true', 'true', 'true', '12345', 'PM', 'ProductManager');
-- -- -- , projecttype_id,  teaminfo_id, workingconditions_id  ,'2','3','4'
--
-- INSERT INTO project ( active, created, customer, description, draft, end_terms, func_direction,  gost_doc,
--                      problem_to_solve, proj_stage, projectauthor,  project_name, stakeholder_number,
--                      subject_area, technology,  updated)
--                      VALUES
--                         ('true','2021-12-01 00:52:05.860462','Савельев','создание сервиса по автоматизации производства','false',
--                          '14-04-2022','автоматизация производства','true','разработка сервиса, подключение БД','с нуля','Победа Александр','Орбита',
--                          '2','онлайн сервис по автоматизации производства','Spring, instagram','2021-12-01 00:52:05.860462');
--
-- INSERT INTO projecttype (isfromscratch, ismvp, ispo, ispaytype)
--                     VALUES
--                     ('true','true','true','true');
--
--
-- WITH data(active, created, customer, description, draft, end_terms, func_direction,  gost_doc,
--           problem_to_solve, proj_stage, projectauthor,  project_name, stakeholder_number,
--           subject_area, technology,  updated, isfromscratch, ismvp, ispo, ispaytype) AS (
--     VALUES                              -- provide data here
--     ('true','2021-12-01 00:52:05.860462','Савельев','создание сервиса по автоматизации производства','false',
--      '14-04-2022','автоматизация производства','true','разработка сервиса, подключение БД','с нуля','Победа Александр','Орбита',
--      '2','онлайн сервис по автоматизации производства','Spring, instagram','2021-12-01 00:52:05.860462', 'true','true','true','true') -- see below
--
-- )
--    , ins1 AS (
--     INSERT INTO project (active, created, customer, description, draft, end_terms, func_direction,  gost_doc,
--                          problem_to_solve, proj_stage, projectauthor,  project_name, stakeholder_number,
--                          subject_area, technology,  updated)
--         SELECT active, created, customer, description, draft, end_terms, func_direction,  gost_doc,
--                problem_to_solve, proj_stage, projectauthor,  project_name, stakeholder_number,
--                subject_area, technology,  updated        -- DISTINCT? see below
--         FROM   data
--         -- ON     CONFLICT DO NOTHING       -- UNIQUE constraint? see below
--         RETURNING active, created, customer, description, draft, end_terms, func_direction,  gost_doc,
--             problem_to_solve, proj_stage, projectauthor,  project_name, stakeholder_number,
--             subject_area, technology,  updated, id AS project_id
-- )
--    , ins2 AS (
--     INSERT INTO projecttype (project_id, isfromscratch, ismvp, ispo, ispaytype)
--         SELECT ins1.project_id, d.isfromscratch, d.ismvp, d.ispo, d.ispaytype
--         FROM   data d
--                    JOIN   ins1 USING (active, created, customer, description, draft, end_terms, func_direction, gost_doc, problem_to_solve, proj_stage, projectauthor, project_name, stakeholder_number, subject_area, technology, updated)
--         RETURNING project_id, id AS projecttype_id
-- )
-- INSERT INTO project(projecttype_id) VALUES (id)
--
--
